url_template: https://rabota.by/search/vacancy?ored_clusters=true&area=1002&professional_role={role}&search_field=name&search_field=company_name&search_field=description&text=&enable_snippets=false&page={page}
headers:
  User-Agent: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Mobile Safari/537.36
datadir: D:/Learning/CarParser/data